name: rebuild dist/ if needed

on: 
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: jnwng/github-app-installation-token-action@v2
        with:
          appId: ${{ secrets.UHA_APP_ID }}
          installationId: ${{ secrets.UHA_INSTALLATION_ID }}
          privateKey: ${{ secrets.UHA_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: build dist/
        run: npm run build
      - run: |
          STATUS=$(git diff --quiet && echo clean || echo modified)
          echo "::set-output name=status::$STATUS"
        id: gitStatus
      - run: |
          echo ${{ steps.gitStatus.outputs.status }}
          echo ${{ contains(steps.gitStatus.outputs.status, 'modified') }}
      - name: Commit dist/ files
        if: contains(steps.gitStatus.outputs.status, 'modified')
        run: |
          git push -u origin master
          git config --global url."https://x-access-token:${{steps.auth.outputs.token}}@github.com/gagoar/".insteadOf  "git@github.com:gagoar/"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "rebuild dist/" -a --no-verify
          git push  push origin HEAD:$GITHUB_HEAD_REF
