name: rebuild dist/ if needed

on: 
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: jnwng/github-app-installation-token-action@v2
        with:
          appId: ${{ secrets.UHA_APP_ID }}
          installationId: ${{ secrets.UHA_INSTALLATION_ID }}
          privateKey: ${{ secrets.UHA_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: build dist/
        run: npm run build
      - run: |
          STATUS=$(git diff --quiet && echo clean || echo modified)
          echo "::set-output name=status::$STATUS"
        id: gitStatus
      - run: |
          echo ${{ steps.gitStatus.outputs.status }}
          echo ${{ contains(steps.gitStatus.outputs.status, 'modified') }}
      - name: Commit changes
        if: contains(steps.gitStatus.outputs.status, 'modified')
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: 'rebuild dist/'
          add: 'dist/'
